/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class TambahFilm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahFilm.class.getName());

    /**
     * Creates new form TambahFilm
     */
    public TambahFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        txtGenre = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Judul Film");

        jLabel2.setText("Genre");

        btnSimpan.setBackground(new java.awt.Color(255, 102, 153));
        btnSimpan.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        jLabel3.setText("Harga");

        txtHarga.addActionListener(this::txtHargaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan)
                    .addComponent(txtJudul, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(txtGenre)
                    .addComponent(txtHarga))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnSimpan)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
    try {
    Connection con = new database.Koneksi().getConnection();
    
    // 1. Simpan data film baru
    // Ganti txtJudul dan txtHarga sesuai nama textfield di form kamu
    String judulBaru = txtJudul.getText();
    int hargaBaru = Integer.parseInt(txtHarga.getText());
    
    String sqlFilm = "INSERT INTO film (judul_film, harga) VALUES (?, ?)";
    
    // PENTING: Gunakan RETURN_GENERATED_KEYS untuk menangkap id_film yang baru dibuat
    PreparedStatement pstFilm = con.prepareStatement(sqlFilm, Statement.RETURN_GENERATED_KEYS);
    pstFilm.setString(1, judulBaru);
    pstFilm.setInt(2, hargaBaru);
    pstFilm.executeUpdate();

    // 2. Tangkap id_film yang baru saja di-generate oleh database
    ResultSet rsID = pstFilm.getGeneratedKeys();
    int idFilmBaru = 0;
    if (rsID.next()) {
        idFilmBaru = rsID.getInt(1); // Mengambil angka id_film
    }

    // 3. Otomatis buatkan jadwal default jika id_film berhasil didapat
    if (idFilmBaru > 0) {
        String sqlJadwal = "INSERT INTO jadwal (id_film, hari, jam) VALUES (?, ?, ?)";
        PreparedStatement pstJadwal = con.prepareStatement(sqlJadwal);
        
        // --- Tambahkan Jadwal 1 (Misal: Senin, 14:00) ---
        pstJadwal.setInt(1, idFilmBaru);
        pstJadwal.setString(2, "Senin");
        pstJadwal.setString(3, "14:00");
        pstJadwal.executeUpdate();
        
        // --- Tambahkan Jadwal 2 (Misal: Rabu, 16:00) ---
        pstJadwal.setInt(1, idFilmBaru);
        pstJadwal.setString(2, "Rabu");
        pstJadwal.setString(3, "16:00");
        pstJadwal.executeUpdate();
        
        // --- Tambahkan Jadwal 3 (Misal: Sabtu, 19:00) ---
        pstJadwal.setInt(1, idFilmBaru);
        pstJadwal.setString(2, "Sabtu");
        pstJadwal.setString(3, "19:00");
        pstJadwal.executeUpdate();
    }

    JOptionPane.showMessageDialog(null, "Film dan Jadwal Otomatis Berhasil Ditambahkan!");
    
    // (Opsional) Kosongkan textfield setelah simpan
    txtJudul.setText("");
    txtHarga.setText("");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal menambah film: " + e.getMessage());
}
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TambahFilm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
