/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import database.Koneksi;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class TampilFilm extends javax.swing.JFrame {
    public void tampilData() {
    // 1. Membuat kerangka kolom tabel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Film");
    model.addColumn("Judul Film");
    model.addColumn("Genre");

    try {
        // 2. Memanggil koneksi yang sudah dibuat
        Koneksi k = new Koneksi();
        Connection con = k.getConnection();

        // 3. Mengambil data dari database
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM film");

        // 4. Memasukkan data ke dalam baris tabel
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_film"),
                rs.getString("judul_film"),
                rs.getString("genre")
            });
        }
        // 5. Menempelkan data ke tabel UI
        tabelFilm.setModel(model);

    } catch (Exception e) {
        System.out.println("Gagal tampil data: " + e.getMessage());
    }
}
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TampilFilm.class.getName());

    /**
     * Creates new form TampilFilm
     */
    public TampilFilm() {
        initComponents();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelFilm = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelFilm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelFilm);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(this::btnTambahActionPerformed);

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnTambah)
                .addGap(18, 18, 18)
                .addComponent(btnUbah)
                .addGap(18, 18, 18)
                .addComponent(btnHapus)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
    TambahFilm formTambah = new TambahFilm();
    formTambah.setVisible(true);
    this.dispose(); // Menutup TampilFilm sementara biar layarnya ga numpuk
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
   try {
            int baris = tabelFilm.getSelectedRow();
            if (baris == -1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Pilih dulu data di tabel yang mau dihapus!");
                return;
            }

            // Jaring pengaman untuk ID
            Object valId = tabelFilm.getValueAt(baris, 0);
            String id = (valId != null) ? valId.toString() : "";

            database.Koneksi k = new database.Koneksi();
            java.sql.Connection con = k.getConnection();
            java.sql.PreparedStatement pst = con.prepareStatement("DELETE FROM film WHERE id_film = ?");
            pst.setString(1, id);
            pst.executeUpdate();

            javax.swing.JOptionPane.showMessageDialog(null, "Yess! Data berhasil dihapus 🗑️");
            tampilData();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal hapus: " + e.getMessage());
        }
    
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    try {
            int baris = tabelFilm.getSelectedRow();
            if (baris == -1) {
                javax.swing.JOptionPane.showMessageDialog(null, "Pilih data yang mau diubah dulu dari tabel!");
                return;
            }

            // Jaring pengaman: Cek null sebelum diubah ke String
            Object valId = tabelFilm.getValueAt(baris, 0);
            String id = (valId != null) ? valId.toString() : "";

            Object valJudul = tabelFilm.getValueAt(baris, 1);
            String judul = (valJudul != null) ? valJudul.toString() : "";

            Object valGenre = tabelFilm.getValueAt(baris, 2);
            String genre = (valGenre != null) ? valGenre.toString() : "";

            // Membuka form UbahFilm
            UbahFilm formUbah = new UbahFilm();
            formUbah.isiData(id, judul, genre);
            formUbah.setVisible(true);
            this.dispose(); 

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Gagal membuka form ubah: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TampilFilm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelFilm;
    // End of variables declaration//GEN-END:variables
}
