/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Asus
 */
public class TransaksiTiket extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransaksiTiket.class.getName());

    /**
     * Creates new form TransaksiTiket
     */
    public TransaksiTiket() {
        initComponents();
        // Background gelap
        this.getContentPane().setBackground(new Color(30, 30, 30)); 

        // Agar font total harga jadi Besar, BOLD, dan warna Kuning Emas
        lblTotal.setFont(new Font("SansSerif", Font.BOLD, 36));
        lblTotal.setForeground(new Color(255, 215, 0));
        lblTotal.setText("0"); // Set nilai awal nol

        // Agar txtHarga tidak bisa diketik manual
        txtHarga.setEditable(false);

        // Memanggil fungsi untuk mengisi dropdown film 
        loadFilm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbFilm = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtKursi = new javax.swing.JTextField();
        cbBayar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnBayar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        cbJadwal = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFilm.addItemListener(this::cbFilmItemStateChanged);
        cbFilm.addActionListener(this::cbFilmActionPerformed);

        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Pilih Film ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Harga Satuan");

        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Jumlah Tiket");

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Nomor Kursi");

        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Metode Bayar");

        txtHarga.setEditable(false);
        txtHarga.addActionListener(this::txtHargaActionPerformed);

        txtJumlah.addActionListener(this::txtJumlahActionPerformed);
        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahKeyReleased(evt);
            }
        });

        cbBayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "QRIS", "Cash", "Debit" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("TOTAL HARGA");

        btnBayar.setText("Bayar & Cetak");
        btnBayar.addActionListener(this::btnBayarActionPerformed);

        lblTotal.setText("-");

        cbJadwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Jadwal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cbJadwal, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbFilm, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel7)))
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnBayar)))
                        .addGap(115, 115, 115))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(btnBayar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadFilm() {
        cbFilm.removeAllItems();
        cbFilm.addItem("-- Pilih Film --");
        try {
            Connection con = new database.Koneksi().getConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT judul_film FROM film");
            while(rs.next()) {
                cbFilm.addItem(rs.getString("judul_film"));
            }
        } catch (Exception e) {
            System.out.println("Error load film: " + e.getMessage());
        }
    }
    private void cbFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilmActionPerformed
    if (cbFilm.getSelectedIndex() > 0) {
    try {
        String judul = cbFilm.getSelectedItem().toString();
        Connection con = new database.Koneksi().getConnection();
        PreparedStatement pst = con.prepareStatement("SELECT harga FROM film WHERE judul_film = ?");
        pst.setString(1, judul);
        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            txtHarga.setText(rs.getString("harga"));
        }
    } catch (Exception e) {
        System.out.println("Error tampil harga: " + e.getMessage());
    }
} else {
    txtHarga.setText("");
}
    }//GEN-LAST:event_cbFilmActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void txtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyReleased
    try {
    if (!txtJumlah.getText().isEmpty() && !txtHarga.getText().isEmpty()) {
        int harga = Integer.parseInt(txtHarga.getText());
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int total = harga * jumlah;
        lblTotal.setText(String.valueOf(total)); // Otomatis nulis angka gede di label
    } else {
        lblTotal.setText("0");
    }
} catch (NumberFormatException e) {
    lblTotal.setText("0"); // Kalau user iseng ngetik huruf, balikin ke nol
}
    }//GEN-LAST:event_txtJumlahKeyReleased

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
    try {
    // 1. Cari ID Film berdasarkan judul yang dipilih
    String judul = cbFilm.getSelectedItem().toString();
    int idFilm = 0;
    Connection con = new database.Koneksi().getConnection();
    PreparedStatement pstId = con.prepareStatement("SELECT id_film FROM film WHERE judul_film = ?");
    pstId.setString(1, judul);
    ResultSet rsId = pstId.executeQuery();
    if (rsId.next()) {
        idFilm = rsId.getInt("id_film");
    }

    // 2. Simpan ke database tiket
    String sql = "INSERT INTO tiket (id_film, nomor_kursi, jumlah_tiket, metode_bayar, total_harga) VALUES (?, ?, ?, ?, ?)";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setInt(1, idFilm);
    pst.setString(2, txtKursi.getText());
    pst.setInt(3, Integer.parseInt(txtJumlah.getText()));
    pst.setString(4, cbBayar.getSelectedItem().toString());
    pst.setInt(5, Integer.parseInt(lblTotal.getText()));

    pst.executeUpdate();

    // 3. Notifikasi Berhasil
    JOptionPane.showMessageDialog(null, "Pembayaran Berhasil! Data tersimpan ke database. 🎟️");
 // Membuka form CetakTiket dan mengirim data transaksinya dengan URUTAN YANG BENAR
    // Membuka form CetakTiket dan mengirim data transaksinya dengan URUTAN YANG BENAR
    CetakTiket struk = new CetakTiket();
    struk.tampilkanStruk(
        cbFilm.getSelectedItem().toString(),   // 1. Judul Film
        cbJadwal.getSelectedItem().toString(), // 2. Jadwal (Waktu)
        txtKursi.getText(),                    // 3. Nomor Kursi
        lblTotal.getText(),                    // 4. Total Harga
        cbBayar.getSelectedItem().toString()   // 5. Metode Bayar <--- PASTIKAN PAKAI INI
    );
    struk.setVisible(true);

    // 4. Bersihkan form buat transaksi selanjutnya
    cbFilm.setSelectedIndex(0);
    txtHarga.setText("");
    txtJumlah.setText("");
    txtKursi.setText("");
    lblTotal.setText("0");

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal Bayar: " + e.getMessage());
}
    }//GEN-LAST:event_btnBayarActionPerformed

    private void cbFilmItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFilmItemStateChanged
    if (cbFilm.getSelectedIndex() > 0) {
        try {
            // Ambil id_film berdasarkan judul
            String judul = cbFilm.getSelectedItem().toString();
            Connection con = new database.Koneksi().getConnection();
            
            // Query ambil harga dan jadwal
            String sqlJadwal = "SELECT id_jadwal, hari, jam FROM jadwal WHERE id_film = (SELECT id_film FROM film WHERE judul_film = ?)";
            PreparedStatement pst = con.prepareStatement(sqlJadwal);
            pst.setString(1, judul);
            ResultSet rs = pst.executeQuery();
            
            cbJadwal.removeAllItems();
            cbJadwal.addItem("- Pilih Jadwal -");
            while (rs.next()) {
                // Format: Hari - Jam
                cbJadwal.addItem(rs.getString("hari") + " - " + rs.getString("jam"));
            }
            
            // (Tambahkan kodingan ambil harga yang sudah kamu punya sebelumnya di sini)
            
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_cbFilmItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransaksiTiket().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JComboBox<String> cbBayar;
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbJadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKursi;
    // End of variables declaration//GEN-END:variables
}
